version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
  pre_build:
    commands:
      - echo "Listing files..."
      - ls -la
  build:
    commands:
      - echo "No build step required for this Python application."
  post_build:
    commands:
      - echo "Cleaning up..."
      - rm -rf venv .git

artifacts:
  files:
    - '**/*'
